
== Vitalik Buterin's Blog 

Link: https://vitalik.ca/

Blog maintained by Ethereum Cofounder and Ethereum Foundation chief research scientist Vitalik Buterin. His blog details the latests research into Ethereum. It convers the protocols, concensus and gametheory pertinante to the network's planned and recent developments, and Vitalik's other interests.  

=== What is the planned fault tollerance for Casper FFG?
===== 37% fault tolerance or 86% bad actors. 
===== 33% fault tolerance or 66% bad actors. 
===== 66% fault tolerance or 33% bad actors. 

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
33% fault tolerance or 66% bad actors. 
----
+++ </div></details> +++


=== What is Vitalik's main critic of voting as a blockchain governance tool?
==== Poor Voter Participation
==== Concensus
==== Volatility

+++ <details><summary> +++
Context
+++ </summary><div> +++
----
 Loosely coupled coin voting is a form of blockchain governance which equates coins with votes. Although, more commonly associated with DPOS systems, Ethereum has a history of voting for blockchain governance e.g. The DAO proposal votes. 
----
+++ </div></details> +++

+++ <details><summary> +++
Answer
+++ </summary><div> +++
----
Poor Voter Participation
----
+++ </div></details> +++


What problem does Ethereum solve with staking by requing people place their Ether at risk?

+++ <details><summary> +++
Answer 
+++ </summary><div> +++
----
The nothing at stake problem
----
+++ </div></details> +++

== OpenZeppelin

Link: https://blog.zeppelin.solutions/

OpenZeppelin is a framework / libary for smart contracts proven to be secure when deployed on the Ethereum Virtual Machine. It's an open source project compatible with modern web software, such as node.js. OpenZepplin's popular contracts are used in projects like OmiseGo and StorJ. 

=== Which keyword is used in Solidity to ensure that a condition is true before execution. 

==== Require()
==== True()
==== IsTrue()

[small]
----
hint: The keyword's arguments are required 
----

+++ <details><summary> +++
Answer 
+++ </summary><div> +++
----
Require()
----
+++ </div></details> +++

Where are Ethereum's smart contracts run? 

+++ <details><summary> +++
Answer 
+++ </summary><div> +++
----
The Ethereum Virtual Machine
----
+++ </div></details> +++

== ConsenSys

Link: https://medium.com/@ConsenSys

ConsenSys is a blockchain software technology company founded in 2015 to accelerate blockchain technology and adoption. The fund projects, make talent avaliable and have launched some of the most successful ICOs to date. 

=== Which Ethereum Cofounder also founded the Blockchain accelerator, incubator and technology company ConcenSys? 

==== Joseph Lubin
==== Arnold Shwarzneger
==== Vitalik Buterin

+++ <details><summary> +++
Answer 
+++ </summary><div> +++
----
Joseph Lubin
----
+++ </div></details> +++



== BlockChannel

Link: https://medium.com/blockchannel

BlockChannel is a new media & educational hub focused on the socio-cultural/economic issues related to blockchain technologies.The BlockChannel podcast focuses on Bitcoin, Ethereum and Zcash. They are also working on decentralized media platforms and solutions. 

Augur is an betting platform built on Ethereum that allows you to bet on what?

+++ <details><summary> +++
Answer 
+++ </summary><div> +++
----
future events
----
+++ </div></details> +++

=== Which popular cryptocurrency uses zero-knowledge proofs to anonymously send transactions? 
==== Zcash
==== Komodo
==== Bitcoin

+++ <details><summary> +++
Answer 
+++ </summary><div> +++
----
Zcash

----
+++ </div></details> +++

== Epicenter

Link: https://www.youtube.com/user/epicenterbtc 

Epicenter hosts weekly interview with prominate crypto figures. They have one the more extensive guest list in the niche. Interviewing founders, venture capitalists and cryptographers, Epicenter is a great resource for staying on top of what happening. The content is focused more on the everyday user and when the subject matter does get technical it is normally followed by explination.  

=== Is Karl Floersch an Ethereum Cofounder? 
==== No Karl is just a popular dev.
==== Yes Karl is Ethereum Cofounder.
==== No Karl is just a popular musician.

+++ <details><summary> +++
Answer 
+++ </summary><div> +++
----
No Karl is just a popular dev.

----
+++ </div></details> +++

== Coindesk 

Link: https://www.coindesk.com/ 

Founded in May 2013, CoinDesk is the leading digital media, events and information services company for the crypto asset and blockchain technology community. Its mandate is to inform, educate and connect the global community as the authoritative daily news provider dedicated to chronicling the space.

=== Filesharing company Bittorrent has partnered with which major cryptocurrency? 
==== Tron
==== Tor
==== Telegram
+++ <details><summary> +++
Answer 
+++ </summary><div> +++
----
Tron
----
+++ </div></details> +++



== ETH Research 

Link: https://ethresear.ch/ 

ETH Research is a semi-public forum for participating in Ethereum’s research efforts. The forum has a technical subject matter and assumed knowledge. It is not a place for general questions or discussion about Ethereum. It focuses on researching protocol improvements, economic systems and solving the scalability problem. 

=== What is a BLS signature? 

==== It stands for Boneh–Lynn–Shacham. BLS signatures are Cryptography that allows a user to verify that a signature (signed with private keys) is legitiamte. BLS signatures use Elliptic curve maths, and share other similarities with schnorr signatures.

==== It stands for Boneh–Klayd–Shacham. BLS signatures are Cryptography that allows a user to verify that a signature (signed with private keys) is legitiamte. BLS signatures use Elliptic curve maths, and share other similarities with schnorr signatures.

==== It stands for Boneh–Lynn–Shacham. BLS signatures are Cryptography that allows a user to verify that a signature (signed with private keys) is legitiamte. BLS signatures use Elliptic circle maths, and share other similarities with schnorr signatures.

+++ <details><summary> +++
Answer 
+++ </summary><div> +++
---- 
It stands for Boneh–Lynn–Shacham. BLS signatures are Cryptography that allows a user to verify that a signature (signed with private keys) is legitiamte. BLS signatures use Elliptic curve maths, and share other similarities with schnorr signatures.
----
+++ </div></details> +++



== Hacking, Distributed 

Link: http://hackingdistributed.com/ 

Hacking Distrubted is a blog by Emin Gün Sirer and his team. This team are behind significant projects and improvements like Bitcoin NG and the Falcon relay network. He is a leader in his field, and authority in blockchain / cryptocurrency. The blog details pitfalls and problems in the space as well as insite into what we can expect moving forward. 

=== Emin Gün Sirer is working on what consensus protocol with the anonymous Team Rocket? 
==== Apalache
==== Avalanche
==== Apach

+++ <details><summary> +++
Answer 
+++ </summary><div> +++
---- 
Avalanche
----
+++ </div></details> +++


== Unenumerated

Link: http://unenumerated.blogspot.com/

Nick Szabo's blog is truely a gem. An early proponent of peer to peer cash, Nick Szabo has posts which predate the Bitcoin whitepaper calling for proof of work algorithms on decentralised networks. All of his posts are an interesting read, and to this day provide some of the best descriptions and explinations of the fundamentals behind bitcoin, smart contracts and other key crypto concepts.  


=== A block chain can hold cryptocurrency as collateral (like an escrow) which incentivizes off-chain performance that can be verified on-chain. What is the off-chain actor often called? 
==== An Oracule
==== An Oracli
==== An Oracle


+++ <details><summary> +++
Answer 
+++ </summary><div> +++
---- 
An Oracle
----
+++ </div></details> +++


== Chris Burniske 

Link: https://medium.com/@cburniske

Chris Burniske was co-author of the book Cryptoassets. He provided investors a framework to evaluate and understand cryptocurrency at a time where there was very little information on the subject. Now an authority in the space, prolific publisher and blockchain product lead, his works are definitely worth a read. 

=== ARKInvest was the first public fund to invest in what? 
==== Ethereum
==== Bitcoin
==== Zcash
+++ <details><summary> +++
Answer 
+++ </summary><div> +++
---- 
Bitcoin
----
+++ </div></details> +++


== Great Wall of Numbers

Link: http://www.ofnumbers.com/

Tim Swanson is the founder and director of research at Post Oak Labs. At the Great Wall of Numbers domain,he has published some of the most insitefull and indepth dives into bitcoin fundamentals. He is a seasoned ecconomist and is currently an advisor at hyperledger. Well worth a read. 

=== Does more efficient mining equipment reduce the electricity usage of Bitcoin? 
==== Yes, more efficient mining equipment only increases the difficulty of bitcoin mining.
==== No, more efficient mining equipment only decreases the difficulty of bitcoin mining.
==== No, more efficient mining equipment only increases the difficulty of bitcoin mining.

+++ <details><summary> +++
Answer 
+++ </summary><div> +++
---- 
No, more efficient mining equipment only increases the difficulty of bitcoin mining. 
----
+++ </div></details> +++


== BlockChannel 

Link: https://soundcloud.com/blockchannelshow

BlockChannel, is a crypto show dedicated to educating the world on the power of blockchain based technologies like Bitcoin, Ethereum, and ZCash. Episodes whenever we feel like it - deal with it. Creator: Steven McKie.

=== What's the name of the platform trying to put Geo-Spatial mapping on the Ethereum blockchain? 
==== Foam
==== Soap
==== Sponge

+++ <details><summary> +++
Answer 
+++ </summary><div> +++
---- 
Foam
----
+++ </div></details> +++


== Unchained Podcast
In this podcast, host Laura Shin, an independent journalist covering all things crypto, talks with industry pioneers about how crypto assets and blockchains will change the way we earn, spend and invest our money. Tune in to find out how Web 3.0, the decentralized web, will revolutionize our world.

=== What’s Riccardo Spagni Twitter handle?

==== Fluffy Pony
==== Fluffy horse
==== Flight unicorn

+++ <details><summary> +++
Answer 
+++ </summary><div> +++
---- 
Fluffy Pony
----
+++ </div></details> +++



== https://itunes.apple.com/us/podcast/conspiratus/id1335928646?mt=2[Conspiratus Podcast]

Conspiratus is Latin for consensus. Through discourse and discussion, we attempt to reach consensus on the state and future of distributed consensus and decentralization technologies.

=== What is this? 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f 
==== a hash of the Genesis Block of the Bitcoin blockchain
==== the example of password
==== address of Ethereum account

hint: The Times 03/Jan/2009 Chancellor on brink of second bailout for banks”.

+++ <details><summary> +++
Answer 
+++ </summary><div> +++
---- 
a hash of the Genesis Block of the Bitcoin blockchain
----
+++ </div></details> +++



== https://noded.org[Noded]

Noded Bitcoin Podcast is co-hosted and produced by Michael Goldstein and Pierre Rochard to provide current events, technical news, and commentary to the Bitcoin community.

Both are founders of the Satoshi Nakamoto Institute, software engineers, and graduates of the University of Texas.

== Bitcoin
=== Bitcoin: A Peer-to-Peer Electronic Cash System
Link: https://bitcoin.org/bitcoin.pdf


Bitcoin is a system for electronic transactions without relying on trust, coins made from digital signatures, which provides strong control of ownership, and also prevent double-spending by a peer-to-peer network using proof-of-work to record a public history of transactions that makes it computationally impractical for an attacker to change if honest nodes control a majority of CPU power.

=== What are the features of a proof of work system?
==== It implements a distributed timestamp server on a peer-to-peer basis
==== It solves the problem of determining representation in majority decision making
==== To compensate for increasing hardware speed and varying interest in running nodes over time, the proof-of-work difficulty is determined by a moving average targeting an average number of blocks per hour

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
To compensate for increasing hardware speed and varying interest in running nodes over time, the proof-of-work difficulty is determined by a moving average targeting an average number of blocks per hour
----
+++ </div></details> +++

https://queue.acm.org/detail.cfm?id=3136559

Bitcoin is a product of several decades’ worth of research on digital cash and so practitioners should be skeptical of claims of revolutionary technology. Most of the ideas in bitcoin that have generated excitement in the enterprise, such as distributed ledgers and Byzantine agreement, actually date back 20 years or more. Recognize that your problem may not require any breakthroughs—there may be long-forgotten solutions in research papers.

=== What are the necessary prerequisites for building a ledger for internet use?
==== The ledger should be immutable, append-only meaning you should be able to add new transactions but not remove, modify, or reorder existing ones
==== There should also be a way to obtain a succinct cryptographic digest of the state of the ledger at any time 
==== The ledger should be a global data structure collectively maintained by a mutually untrusting set of participants


+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
The ledger should be a global data structure collectively maintained by a mutually untrusting set of participants
----
+++ </div></details> +++


http://www.fon.hum.uva.nl/rob/Courses/InformationInSpeech/CDROM/Literature/LOTwinterschool2006/szabo.best.vwh.net/idea.html

Smart contracts embed contracts in all sorts of property that is valuable and controlled by digital means, it references the property in a dynamic, often proactively enforced form, and provide much better observation and verification where proactive measures must fall short. Smart contract design has successively refined security protocols which give control of the cryptographic keys for operating the property to the person who rightfully owns that property, based on the terms of the contract. 

=== What are the differences between the crude security system and the rectified security system?
==== A lock to selectively let in the owner and exclude third parties
==== A back door to let in the creditor
==== Creditor back door switched on only upon nonpayment for a certain period
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Creditor back door switched on only upon nonpayment for a certain period of time
----
+++ </div></details> +++


https://www.nytimes.com/2018/01/16/magazine/beyond-the-bitcoin-bubble.html

A mysterious new technology emerges that is the result of two decades of intense research and development by nearly anonymous researchers. Digital property transferred includes digital signatures, digital contracts, digital keys, digital ownership of physical assets such as cars, digital stocks, digital money. All these are exchanged through a distributed network of trust that does not require a central intermediary like a bank where only the owner of an asset can send it, only the intended recipient can receive it, the asset can only exist in one place at a time, and everyone can validate transactions and ownership of all assets anytime they want.

=== What are the criticisms leveled at bitcoin?
==== Merchants will not accept Bitcoin because of its volatility
==== Bitcoin is a haven for bad behavior, criminals and terrorists to transfer money anonymously with impunity
==== It has limited usage by ordinary consumers
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
It has limited usage by ordinary consumers
----
+++ </div></details> +++


https://people.eecs.berkeley.edu/~luca/cs174/byzantine.pdf

The Byzantine Generals Problem, under various hypotheses, have been provided solutions and shown how they can be used in implementing reliable computer systems. These solutions are expensive in both the amount of time and the number of messages required. Achieving reliability in the face of arbitrary malfunctioning is difficult and its solution seems to be inherently expensive. The only way to reduce the cost is to make assumptions about the type of failure that may occur.

=== What are the drawbacks of Byzantine General problem?
==== Oral message is not sufficient to transmit message
==== No solution will work unless two-third of generals are loyal
==== With only three generals no solution can work in the presence of a traitor
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
With only three generals no solution can work in the presence of a traitor
----
+++ </div></details> +++

https://github.com/ethereum/wiki/wiki/White-Paper

The mechanism behind proof of work was a breakthrough in the space because it solved two problems. First, it provided a simple and moderately effective consensus algorithm, allowing nodes in the network to collectively agree on a set of canonical updates to the state of the Bitcoin ledger. Second, it provided a mechanism for allowing free entry into the consensus process, solving the political problem of deciding who gets to influence the consensus, while simultaneously preventing Sybil attacks

=== What are the approaches to building a consensus protocol?
==== Building an independent network
==== Building a protocol on top of bitcoin
==== Building and testing all necessary state transition and networking code

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
---- 
Building and testing all necessary state transition and networking code

----
+++ </div></details> +++

https://e-drexler.com/d/09/00/AgoricsPapers/agoricpapers.html

Agoric computation requires market compatible mechanisms for tha allocation of processor time and storage spaces. Recasting processor scheduling as an auction process yields a flexible priority system. Recasting storage management as a system of decentralized market negotiations yields a distributed garbage collection algorithm able to collect unreferenced loops that cross trust boundaries.

=== Memory systems differ. What features make them different?
==== Latency
==== Access cost
==== Storage cost

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
 Storage cost
----
+++ </div></details> +++

https://medium.com/@cdixon/crypto-tokens-a-breakthrough-in-open-network-design-e600975be2ef
The internet and web were created as open platforms that any user, developer, the organization could access equally. Among other things, this allowed independent developers to build products that quickly gained widespread adoption. Google started in a Menlo Park garage and Facebook started in a Harvard dorm room. They competed on a level playing field because they were built on decentralized networks governed by open protocols

=== What were the innovations of bitcoin?
==== It is a store of value for people
==== It is a new way to develop an open network
==== It can reach the underbanked and unbanked populations

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
It only requires a wallet. Hence it can reach the underbanked and unbanked populations

----
+++ </div></details> +++



== Books to read (highlight a good quote each)
https://www.amazon.com/Mastering-Ethereum-Building-Smart-Contracts/dp/1491971940[Mastering Ethereum]

https://www.manning.com/books/building-ethereum-dapps[Building Ethereum Dapps]

https://www.apress.com/us/book/9781484225349[Introducing Ethereum and Solidity]

https://goethereumbook.org/[Ethereum Development with Go]

https://cryptoeconomics.study/[Cryptoeconomics Study]

https://www.amazon.com/Business-Blockchain-Practice-Application-Technology/dp/1536663468[The business Blockchain]

== Twitter accounts to follow

TBD

== Forums to visit

https://forum.ethereum.org/[The Ethreum Community Forum]

https://www.reddit.com/r/ethdev/[Reddit - r/ethdev]

https://www.reddit.com/r/ethereum/[Reddit - r/ethereum]

https://www.reddit.com/r/ethdapps/[Reddit - r/ethdapps]

https://www.reddit.com/r/CryptoCurrency[r/CryptoCurrency]

https://bitcointalk.org/[Bitcoin Talk]



