== Bitcoin
=== Bitcoin Development (source)
Link: https://lopp.net/bitcoin.html


https://stephanlivera.com/download-episode/942/46.mp3?ref=download[Stephan Livera Podcast]
==== This is a cryptocurrency podcast channel focused on reaching bitcoin software developers, entrepreneurs, business leaders, analysts, economists and more. 
On episode 46 of the podcast, in an interview with Sjors Provoost from the Netherlands who mentioned he had to learn C++ from the basics as this is the language bitcoin code is written in.
The bitcoin technology is getting more complicated, with new work being built on the fundamentals until one day you have to rebuild the entire foundation. The changes in the master branch are usually incremental. Rebasing, which is making changes and rebasing or relaying on the latest version of the master branch. Reviews often can get in the way of each other because of the decentralized nature of the system. There are systems in place to avoid this.  Watch from 10:35-14:30. 
Why use hardware wallets? Keeping your wallets on your hard disk or pc, you are carrying all your money everywhere and its not ideal. Dedicated devices that keep your key safe offline, away from hackers. The drawback though is that it requires software support that sends your public key to the server of the company that made the hardware wallet. This can be easily assessed by any malicious worker, hacker or overzealous law enforcement agent.  Andrew Chow proposed a solution; listen from 20:23-22:46. 


=====  Advantages of hardware wallets
===== Private keys are stored safely and can’t be exported as plain text
===== Immune to computer viruses that teal software wallet

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Can be used securely and interactively. Private keys never need to come in contact with malicious software


----
+++ </div></details> +++


http://cf-media.sndcdn.com/pmLdqVoeFi4z?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vcG1MZHFWb2VGaTR6IiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTQ4MjIxMzQzfX19XX0_&Signature=E2NJ5e7pG6CXDwCoNRtkoTOfQquKrNcWlUaBAAM06ELOZaE5WvV78vAugGDEgfaCOZAWdIHNjc9FBxzHtl0G1WExZueCoDCBw7hFFdF0xKS50p7S1elbD5sisMNlzvHJRdHo4EIzCpDGp-JDiuQDzEqvzqECOFaOuAGXf09BjpN0-fUWVCvomPy8MhQ16fClWce1QxwX1TQJVTcIJFnvBPNiPqmHCpLgqHjQnKNey2EuMfaXLylmyDSqa~IcAze8K-teh6gRnkBWRZufHLOMX4OWYNHebAxbL5f2Z0rPZvfMlarLxk7Ii~~5wnwESbCx7cXuCZCzAM0UrkDU6B2qZA__&Key-Pair-Id=APKAJAGZ7VMH2PFPW6UQ[CRYPTO VOICES]

==== This is a bitcoin podcast run by Matthew Mezinskis and Fernando Ulrich. On the episode 52 of their podcast they had Ragnar Lifthrasir, a real estate professional, Founder of IBREA (International Blockchain Real Estate Association). After being in the real estate industry since 2006, he went back to school in 2009 for his masters in real estate development. He saw an opportunity in the contrast between real estate and bitcoin; real estate is fragmented and centralized while bitcoin offers unity and decentralization. Listen from 3:20-4:49
In theory, Ragnar always says blockchain when talking to people instead of bitcoin because people always think of buying and selling the currency bitcoin but it has other functions such as time stamping, tokenization, multi-signature among others. Tokens can either be utility or proxy tokens. Tokenization in real estate in proxy. Tokenization has different meanings 
i. Using a token to transfer ownership
ii. Using a token to own a portion of ownership
iii. Crowd funding
Tokenization in real estate involves representing the shares of a legal entity with tokens. This same analogy applies to other industries too. This is a security like bond or stock. The downside being compliance and only credited investors being able to purchase these tokens. Using a token to transfer ownership involves signing a deed on the blockchain as opposed to the paper form. Crowd funding involves selling tokens and investing the money in real estate. 
This government plays a minimal role in transfer of ownerships with the government now relegated to the role of a third party/intermediary. They are only required to publish the transfer of ownership. There is still a lot of work being done to incorporate other features like multi-signatures and smart locks. Some companies also now have loans using bitcoin as collateral for high rates and for a shorter term to acquire real estate. 

===== What other industries can tokenization be applied?
===== Medical practice
===== 
Banking Industry
----
+++ </div></details> +++

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Government records
----
+++ </div></details> +++


https://hwcdn.libsyn.com/p/a/e/7/ae70b5890866dc50/7296115-44100-2-ab35ea8bd7e1b.mp3?c_id=29425319&forcedn=attachment&cs_id=29425319&destination_id=583022&expiration=1548231416&hwt=a934bd90aa3ba71c2737f3417eb7457b
 [TALES FROM THE CRYPT]

==== Tales from the crypt is a podcast hosted by Marty Bent who usually has interesting people on to discuss bitcoin. On this episode he has Yassine Elmandjra, Crypto analyst at ARK Invest to discuss topics ranging from bitcoin mining, how he started bitcoin and others. This podcast runs longer than the average length of other podcasts due to the interesting small talk they make during the podcast. Yassine got into bitcoin in 2017 when he and his father decided to do something together. A major selling point of bitcoin for him was the freedom and decentralization of bitcoin especially as he is from a 3rd world country and has seen family lose their wealth due to the unnecessary control government have on currency. The legislation on bitcoin in Morocco is still ambiguous, so there are no local exchanges. The major means of transaction locally is peer-to-peer network. 
As a member of the crypto sphere of twitter, he has been compelled to learn to voice his opinions. Bitcoin is bootstrapped to three main components;
i. Reward mechanism- rewarding honest node behavior during the consensus process
ii. Proof of work- deals with identity and civil attacks
iii. Nakamoto consensus- to prevent double spending
He worked at understanding the mining process. Mining started as a hobby among the first bitcoin adopters in 2009 and was done on desktop computers and is now a professional industry. In 2010, the trend shifted to GPUs. Co-mining was introduced later that year because of the difficulty of mining. 2011 brought the FGEA based miners. Next, we saw the ASIC miners with efficiency now determined by how advanced the node is. 
Foundries produce cutting edge nodes and only two products are relevant to bitcoin. Making cutting edge nodes requires a lot of expenditures in R and D, making it hard for medium and low-level miners to stay competitive. Cost of mining is also affected by electricity costs. This has caused bitcoin miners to explore renewable energy. According to coinshares, bitcoin miners use 77% renewable energy compared to 18% average of other industries.

===== What possible factors affect the price of bitcoin mining?
===== Price of electricity
===== Price of required hardware

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Price of electricity
----
+++ </div></details> +++


http://www.satoshisdeposition.com/podcast/BTCK-247-2019-01-01.mp3
 [BITCOIN KNOWLEDGE -
A Year Decade of Bitcoin in Review]

==== Bitcoin Knowledge is a journalism podcast run by Trace Meyer to help people understand bitcoin better. He is an entrepreneur, investor, journalist, monetary scientist and ardent defender of the freedom of speech.  
2018 started with bitcoin at $14k and ended at $3.7k. This represents a 0.66% decline per day decrease in 2018, about $410bn transactions were made during this period. Ventured capitals accounted for $2.33m in 2012, $120m in 2013, $369m in 2014, $601m in 2015, $597m in 2016, $876m in 2017 and $3.128bn in 2018. ICO investments accounted for $30m in 2014, $9m in 2015, $245m in 2016, $5.5bn in 2017 and $16.7bn in 2018. 
Take note of the trajectory similarity between 2013/2014 has occurred again in 2017/2018. A lot of human capital is being invested in the industry with lawyers, developers, accountants from other industries are being absorbed into the crypto industry. Prices may be down at the moment, but the industry is in forward motion like never before. Proof of keys event will now be done annually on January 3rd; withdrawing bitcoin from all 3rd parties just to be sure we really have them with Hitbtc appearing to have been the first victim as they have stopped withdrawal of funds. 
A noteworthy achievement for bitcoin is no other projects come close in terms of number of quality developers, number of commits getting done, amount of code getting done, amount of research and development.   

===== Proof of keys serves what purpose?
===== To check and balance exchanges
===== To prevent falsifying data by third parties

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
To check and balance exchanges
----
+++ </div></details> +++
===== THE BAD CRYPTO PODCAST

https://ondemand-us-dal01.cdnstream1.com/d/clips/e6cb0305-7c74-4a39-8d62-a896017e2917/020e8074-c5f9-443d-b254-a8c4003fffbc/0e847fb4-ac17-4071-8efb-a8c4004d7442/audio/direct/t1547783003/Bitcoin_Bull_Run_and_How_to_Use_Exchanges.mp3?t=1547783003&publisher=omny&aw_0_1st.program=The+Bad+Crypto+Podcast&aw_0_1st.organization=Aaron+The+Tech&aw_0_azn.pgenre=%5b%22Business%22%5d&aw_0_azn.pname=The+Bad+Crypto+Podcast&listeningSessionID=5c46a5c7df2bbf33_6072532_22__752d973e1786067349f22a49e9fa565328e49392[THE BAD CRYPTO PODCAST]

==== This is a fun and interactive podcast run by two interesting guys, Joel Comm and Travis Wright. The podcast being reviewed was from 2017, around the time BCH forked out from BTC and BTC first peaked at $3.3K. 
Reddit is a good place to gain knowledge about bitcoin. Almost all legitimate coins have their own reddit, so you can go there to interact with their users. There are different points of views and ideas flying around on the bitcoin reddit, this was evident as the need for the bitcoin fork so information gotten there should be taken with a pinch of salt. 
How to use exchanges was explained in detail between 21:31-31:59. It is a little long, but it is basic and step by step. While using exchanges, always make sure you have your 2FA feature turned on to doubly safeguard your assets. Your assets should not be kept in exchange wallets to prevent hackers getting to them as exchanges have been subject to hacks over time. Instead it should be kept in an offline wallet.   

===== What security precautions can you take to safeguard your bitcoin?
===== Do not store your bitcoin on web wallets
===== Store your private keys offline

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Do not store your bitcoin on web wallets
----
+++ </div></details> +++
===== CITIZEN BITCOIN
https://media.simplecast.com/episodes/audio/247752/Ep21.mp3[CITIZEN BITCOIN]

==== This is a bitcoin blog aimed at educating bitcoin enthusiasts run by Brady Swenson and Cannons Call. Episode 21 which we review has a timeline of events that occurred sine the inception of bitcoin until this moment. 
Lindy Effect-The future life expectancy of some nonperishable thing like an idea or technology is proportional to their current age so that every additional period of survival implies a longer remaining life expectancy. Trust is the main issue at play in the issue of bitcoin as it involves money. 
There were previous attempts at creating digital currency that fell through because they were not decentralized enough so they could be shut down. Listen from 08:52-10:54 and 12:28-14:06
Notable Events
 Jan 3rd 2009; the first block was mined by Satoshi Nakamoto and the code was shared on Jan 8th 
 May 2010; Laszlow Hkynyecz sent 10K BTC for 2 pizzas worth $25. First USd value attached to BTC
 2010; BTC broke the penny threshold for the first time in 2010
 2011; BTC broke the $1 threshold for the first time
 Aug 2017; BCH hard fork happened 
 2nd layer of BTC, Lightning network stayed on with the BTC chain. 
 2018; phenomenal growth of lightning network. Network capacity went from 0-515 BTC, public nodes went from 0-4800

===== There are 3 hard forks of BTC. Can you name them?
===== BCH- Bitcoin Cash

===== BTG- Bitcoin Gold


+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
BCH- Bitcoin Cash

----
+++ </div></details> +++


http://dcs.megaphone.fm/PKP3311382414.mp3?key=7280f68e510ed76e169b41acfd25b217&listener=85b50628-e1cd-46cd-b5f4-818c01799214[UNHASHED PODCAST]

==== This is a cryptocurrency podcast channel ran by four guys; Ruben Somsen, Mario Gibney, Bryan Aulds, Colin Aulds.  
We go through the mist important days in the history of BTC
 Oct 31 2008- Satoshi releases the BTC whitepaper
 Jan 12 2009- Alfinni receives 10 BTC from Satoshi
 May 22 2010- Laszlow makes the first purchase with BTC
 June 14 2011- Wikileaks accepts BTC as forms of donations
 Sept 2012- BTC foundation was setup to be the official face of the blockchain
P2SH got added to the soft work. Enabled multi-signatures and makes it more compatible with other wallets
 Oct 2013- FBI seized 26000BTC from Silk Road and arrested its founder Ros William AKA Dread Pirate Robrts for hiring a hitman to kill his partner
 Fe 2014- Mount Gox files for bankruptcy. Highlights the importance of  not keeping your coins on exchanges
 July 2013- Bank depositors in Cyprus lost at least 47% of their holdings above $100K. this highlighted the failings of the banking system and pushed the BTC narrative
 Feb 2015- Number of worldwide merchants exceeded 100,000
Hashrate exceeded 1 hexahash/sec
 Aug 2017- BTC hard fork
 Jan 2018- Lightning Network main net went live with 60 nodes

===== What is the lightning network
===== It is a soft fork of BTC
===== 
It enables fast payments between nodes


+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
It is a soft fork of BTC
----
+++ </div></details> +++


http://cf-media.sndcdn.com/6syoLIy293Qa?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vNnN5b0xJeTI5M1FhIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTQ4MjIzMDcxfX19XX0_&Signature=KAqDEOCTsghcXp24-ABLWp26p1AROG8HM0h~6i0lGd4wQECqjX0BVphfA0dF1tMXK8CfxAgjDq6pvwapmYnWJoWB0oMauNIxh7j3f2ExKe~O9kPcLI7VZMj0tE4CRjciczeuF2n75-BC-3ww5-IBQ1D24yBldzhBDXAepgiVRxqmAbieSh4lsmmeRYgq3IkkDKeHYrYKnFgtBu~NFIplSKhwESFV9SQwR5wtDY8Y7L0ELyS7vcCmkbASQDgLxdbMruC~WmjEAFvpBVsOU9R6mzg3rDe57cbBYnDaJRQDpyeFNGYO52j4uxJZftGkXhYzQ-XtkOOHECesMliNpvuKRA__&Key-Pair-Id=APKAJAGZ7VMH2PFPW6UQ[NODED ]

==== Noded podcast is cohosted by Micheal Goldstein and Pierre Rochard to provide current events, technical news, the bitcoin community. On episode 0.23.0 they have an interactive Q and A session.
Listen from 34:09 to 35:10. Questions about the monetary policy of BTC and why Satoshi put most of the 21 million BTC into the hands of the few early adopters. 
The HODL crowd are fundamental to maintaining the price of BTC. Imagine everyone wanted to sell. Who would want to buy? The price will come plummeting down to zero
Bitcoin is a deflationary coin and there are two schools of thoughts about deflationary coins. The Keynesian and Austrian Economics schools of thought. 
A Fred Wilson blog post was deconstructed and analyzed (13:10-29:35) and it was agreed he was not being very knowledgeable and intellectual.

===== Advantages of a decentralized currency
===== It is apolitical and without borders so everyone can adopt it especially those in countries with failing central powers
===== Payments are borderless, removing the exorbitant fees for international transfers

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
It is apolitical and without borders so everyone can adopt it especially those in countries with failing central powers



https://hwcdn.libsyn.com/p/8/d/5/8d54dd6be14ccc86/Off_the_Chain_with_Murad.mp3?c_id=24992840&forcedn=attachment&cs_id=24992840&destination_id=770844&expiration=1548232571&hwt=0d29979a6cad1780b214953dcccf1657[OFF THE CHAINS]

==== What is BTC? Listen from 3:34-3:50
Core components of BTC
 Blockchain
 Proof of Work (5:29-8:16)
The Nakamoto Consensus prevents double spending in BTC while you need lot of trust that here is no double spending in a centralized system that we see in Central Banks and commercial banks. BTC not being able to print more than 21 million units makes it extremely scarce and it is its most important asset. Listen from 22:3-22:47. Gold expands at about 1.6%/year while the rate of expansion of BTC gets lower every year. In an inflationary system, people with assets in currency will decrease in value while the inflation rate will raise the value of assets and vice versa for a deflationary system. 
Can BTC value go to zero? Listen from 52:12-52:46
Volatility is needed for BTC to actually become the global reserve. BTC aims to be a net positive volatile asset for this purpose
An irony is the people who need to excessive control want minimal control for themselves. Listen from 1:22:55-1:24:42

===== Why is Bitcoin volatile?
===== Emotions of bitcoin holders. When prices fall, people sell in panic



===== Bitcoin prices react to the news

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Emotions of bitcoin holders. When prices fall, people sell in panic



----
+++ </div></details> +++

https://media.simplecast.com/episodes/audio/219275/WGMG-03.mp3[WHAT GRINDS MY GEAR]

==== A unique all female podcast cohosted by Jill Carlson and Meltem Demirors.
Coinbase announced stable coins with back doors to prevent users violating regulations which can lead to asset seizure. Idax also announces they will be blocking New York based IP addresses. Are we still decentralized? Is decentralization only a term for rallying cry or a weapon?
Removal of intermediaries and trusted 3rd parties on exchanges is a huge step on exchanges towards decentralization. But features such as KYC, AML, tracking customers does not enable privacy which is an important part of decentralization. 
We might have to accept this new level of BTC price as normal and that last years run was the exception. The consensus is that BTC will also suffer with the macro market and BTC will be seen as a risk asset. 

===== Features of a decentralized exchange
===== Users do not transfer their assets to the exchange
===== 
Do not typically falsify trading volumes


+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Users do not transfer their assets to the exchange
----
+++ </div></details> +++


http://d1dwvcwq657ipv.cloudfront.net/episodes/original/24627957?episode_id=16811496&response-content-disposition=attachment%3Bfilename%3D%22willy_final_audio.mp3%22&Expires=1548905015&Signature=BsD5BCyqWGEBPo9QwXAIAlTZHYCXwb4RIIjzbq8BChO6rEHoJ8D8uYjO-3Wv7PCtmoKrehCpaeL%7EMTHpDh74WfJRh8N6lmMAXCWZTbXvNNrmvdeG0C4BB-ozZSchQ1DMeCeH6ibEiox4Hmc-qaNX3oSGU8K9zWvguRspdoyWHUo_&Key-Pair-Id=APKAJBD223KRVW6VKWSA[THE COINPOD PODCAST]

==== A BTC podcast run by Zack Voell. We review episode 42 where he talks to Willy Woo, a technical analyst, engineer and hardcore bitcoineer about the challenges and nuances of on-chain data analytics.
Willy first heard of BTC in 2013 when it cracked the $1bn market cap. It was branded the digital gold and as an investor in gold, he got interested. Got to working on BTC proper between 2015 and 2016. BTC drives the alt markets. Alt coins magnify BTC price action. They are highly volatile and don’t outperform BTC. In the short term, Alt coins can increase returns while in the long run, they are increases risk, reduced return. Picking the right Alt coin in a bull run, you can get a slight leverage over BTC as they have a higher volatility and you go back to BTC in a bear run.
There are 3 broad categories of Alt coins. Listen from 13:48-17:12
Volatility of BTC in 2019 will be no different from other FIAT currencies. This is due to the changing landscape and the somewhat more level of expertise in the level of starting to look like FOREX. 

===== what are the three categories of cryptocurrencies
===== Bitcoin

===== Alt coins


+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Bitcoin

----
+++ </div></details> +++


https://unchainedpodcast.com/?spp_download=1e4f25852b587cdb84d6992f9f407de9[UNCHAINED]

==== Laura Shin is a decorated journalist with a journalism degree from Stanford University and master of arts from Columbia University’s School of Journalism. In the episode 99 of the podcast, Wences Casares, the “so-called” patient zero of bitcoin in the valley is the CEO bitcoin vault and wallet company XAPOS 
After seeing his family lose their wealth 3 times because of the actions of the central banks in his native country Argentina, he was quickly bought over by the prospect of an apolitical, decentralized currency. Listen from 04:58-06:41. He still believes the government is needed, but only playing a minimal role
When the government banned money transfer into Argentina in 2011, he was forced to look into other options to circumvent the government restrictions when he discovered Bitcoin. The relatively stable financial situation in the US to explain the necessity of BTC to people there. Converting BTC to local currency in different countries is still subject to the prevalent system there. 
Bitcoins of their customers are usually kept in deep storage in 5 bank locations in Switzerland. Servers that have never been online are used for the storage and require 3 private keys to access. He relishes other custody solutions coming into the scene since this is what is best for BTC. He also believes that BTC will be a global standard of value and not just the currency of the dominant power. Listen from 45:35-48:35.

===== Question- what countries have banned bitcoin


===== ecuador
===== China

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
ecuador
----
+++ </div></details> +++
===== LET’S TALK BITCOIN

https://hwcdn.libsyn.com/p/b/7/7/b77eece3e6d452e9/LTBE375PRC.mp3?c_id=23318512&cs_id=23318512&expiration=1548223297&hwt=085c538d9256fffbfe047726a35777cb[LET’S TALK BITCOIN]

==== On this episode 375 featuring Adam Levine, Stephanie Murphy, Jonathan Mohan, Joe Looney they talk about the obsolete Bitcoin Alert system.
As we progress, we have grown out of somethings while others have bee simply deemed unnecessary. One of such features is the Bitcoin Alert system. The idea was to communicate emergencies within the network to the participants that was authenticated and propagated from the 3 or 4 people with access to these keys. People believed their opinions mattered more and would treat it with more importance, which is against the decentralized nature of the system. The problems arose because of the anonymity of some holders of this key. If they got compromised, someone can propagate a malicious message on this network and it would get treated with importance. The alert was only used to piece back a 26-block hard fork that would have occurred. What was an emergency channel has now become a liability that can be easily exploited.

===== Who were the holders of the bitcoin alert system keys

===== satoshi nakamoto
===== Gavin Andresen

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
satoshi nakamoto
----
+++ </div></details> +++


http://hwcdn.libsyn.com/p/9/4/a/94afbf845f1d48f5/WBD057.mp3?c_id=29408600&cs_id=29408600&expiration=1548230650&hwt=018170a5f7d3875e86e16f14455b1bcb[WHAT BITCOIN DID]

==== Bitcoin podcast hosted by Peter McCormack with Bryan Bishop on as a guest. Bryan is a core developer of Bitcoin and they discuss the intricacies involved in Bitcoin development.
Bryan first heard of Bitcoin in January 2009 when it only ran on windows. He concluded it was another idealistic scam that would die off. But he soon found that BTC was different from other development projects because
 BTC is an open source project
 BTC is decentralized without an organization responsible for developing it
The first set of people to contribute to BTC development did it as a hobby before it became a paying industry later.  Bitcoin.org and bitcoin core website require a lot of basic testing infrastructure and these are good points to start contributing to Bitcoin development for a newbie since the are easier. Listen from 15:10-16:35. These are people hat can make changes to BTC
BIPs (Bit Improvement Proposals) are what you need to propose changes to the blockchain. A prototype is usually made with the BIP and submitted. When it has passed as ready and good, it can be added to the live code.
A hard fork is an incompatible change in the rules while soft fork is compatible. Soft fork is a further restriction of the rules, something that was originally valid becomes invalid while hard fork is vice versa. The hard fork is usually incompatible with the old version. He does not believe any hard forks are coming up in BTC. Things that need to be changed can be achieved with a soft fork.
People without technical knowledge can simply share knowledge and materials to help spread the ideology of BTC among the general public

===== Types of BIP
===== Standard Track
===== Information

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Standard Track
----
+++ </div></details> +++



http://hwcdn.libsyn.com/p/9/4/a/94afbf845f1d48f5/WBD057.mp3?c_id=29408600&cs_id=29408600&expiration=1548230650&hwt=018170a5f7d3875e86e16f14455b1bcb[BITCOIN UNIVERSITY]

==== TRANSACTIONS DECONSTRUCTED WITH JEFF FLOWERS
Transaction is the movement of value on the network. It is broadcasted to all BTC nodes. Inputs are the source of funds being moved. Output is the creation of an unspent transaction output (UTXO) denominated in Satoshis. A transaction completely depletes the UTXO involved. When only a portion is required, a change is required. The change is unspent UTXO and the difference between new UTXO and change is taken as the network fee.
STANDARD TRANSACTIONS
i. Pay to Public Key Hash (P2PKH)- constructed in the scriptsig form
ii. Pay to Public Key- outdated compared to P2PKH. Shorter but less secure
iii. Multisig- it is an M of N scheme where there is an N number of keys and a minimum of M is needed to create a transaction. Presently limited to a maximum of 15 listed public keys
iv. Data Output- this is the allure of blockchain as a single source of shared truth embodied by an immutable database opens up a lot of possibilities. OP_RETURNS allows for 40 bytes of data to be stored on the blockchain
v. Pay to Script Hash (P2SH)- payment here instead of going to a potentially complex locking script rather go to the hash of the script. Shortens the size of the transaction. 


===== Types of standard transactions
===== P2PKH
===== P2PKH

+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
P2PKH
----
+++ </div></details> +++
==== SOCIAL MEDIA BITCOIN

==== The twitter presence of Bitcoin enthusiasts and developers is a closely-knit circle you don’t just stumble upon except you actively look to get into that sphere. Once inside, it is a safe place relatively. This is the internet remember? There are 117 BTC developers o the Twitter group and 676 subscribers. Lightning has 59 members and 325 subscribers. This makes sense as they are the new kids on the block. There are very few overlaps between the members of the lightning developers and bitcoin developers with the name Elizabeth Stark standing out. Elizabeth also happens to be the highest ranking influential female in the Bitcoin industry standing at number 7. Andreas Antonopoulos, a Greek-British bitcoin developer is the mist influential person in the Bitcoin industry. Garven Andresen, who was declared by Satoshi Nakamoto as the lead developer of Bitcoin and is number 8 on the list. 
Crypto law has 82 members and 434 subscribers. These are lawyers, advocates and legal practitioners who are integral to he operation of Bitcoin as it is usually on the periphery of the law and thrives on exploiting grey areas to make governments and central powers relinquish the unnecessary amount of power they hold on currency and freedom.

===== 
===== 
===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++
==== Introduction to bitcoin

==== Bitcoin a unit of currency is the collection of concept and technologies running through a digital money ecosystem in which users are connected through the internet made available by an open source software, it is fast reliable and secure means of exchange in that it is decentralized meaning there is no central control server or point of control that is created through a process called mining.Bitcoin was invented in 2008 by satoshi nakamoto and the network started fully in 2009, though virtual, bitcoin can be used as means of exchange for both high and low value retail, offshore conduct services and payment means of import and export. Bitcoin wallet is a client application through which bitcoin can be accessed, choice of wallet depends on individuals with some more secure than the others; they include desktop wallets, mobile wallets, hardware wallets and paper wallets.Based on degree of autonomy wallets include full node client which may consume large computer resources and lightweight client, getting a first bitcoin could be challenging for new users but means like offering services in exchange for bitcoin, meeting a friend who wants to sell or finding sellers in networks, also there are bitcoin ATMs available in cities, the current price of BTC is being set by market value and so fluctuates, but many mobile applications and web networks provide current market values, A wallet address allows irreversible transactions to be carries out between users and typically starts with a 1 or a 3,there is also an option of scanning a QR code on a smartphone which corresponds to same wallet address of the user.
===== What are the difference between bitcoin and traditional currency?
===== Bitcoin is virtual, traditional currency isn’t
===== bitcoin transactions are reversible traditional currency transactions are not
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
bitcoin transactions are reversible traditional currency transactions are not
----
+++ </div></details> +++
==== How Bitcoin Works

==== Bitcoin system is based on decentralized system trust and a transaction becomes trusted and accepted, recorded on a block chain produced by miners. A block chain explore is a web app that operates as BTC search engine and allows to search for transactions, addresses and blocks to see relationship and flow between them.Inputs (debits) and outputs (credit) do not add up to same amount with outputs adding up less than inputs because of transaction fees collected by miners. A transaction forms a chain where the inputs from latest transaction corresponds to outputs from previous transactions. Mining nodes validate all transactions by reference to bitcoin’s consensus rules. Therefore, mining provides security for bitcoin transactions by rejecting invalid or malformed transactions.
===== What does mining process do?
===== Mining achieves a fine balance between cost and reward.
===== Mining nodes validate all transactions by reference to bitcoin’s consensus rules
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Mining nodes validate all transactions by reference to bitcoin’s consensus rules
----
+++ </div></details> +++
==== Bitcoin Core: The Reference Implementation

==== Bitcoin is an open source project meaning its simply free to use and also developed by an open community of volunteers. For a developer, there is need to set up a development environment with all the tools, libraries, and support software for writing bitcoin applications in order to access operating system’s command-line interface known as a shell, accessed via a terminal application through which series of commands and scripts can be run. These includes compiling bitcoin core from the source code, selecting a bitcoin core release, configuring the bitcoin core build to building the bitcoin core executables which can take some time depending on CPU speed and available computer memory. There are many alternative clients, libraries, toolkits, and full-node implementations in the bitcoin ecosystem. These are implemented in a variety of programming languages, offering programmers native interfaces in their preferred language.
===== Reasons for running a bitcoin node?
===== If a user does not want to rely on any third party to process or validate transactions.
===== If you are developing bitcoin software and need to rely on a bitcoin node for programmable (API)
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
If you are developing bitcoin software and need to rely on a bitcoin node for programmable (API)
----
+++ </div></details> +++
==== Keys, Addresses

==== Bitcoin is based on cryptography, which is a branch of mathematics used extensively in computer security. Cryptography is a Greek word meaning secret writing”. Ownership of bitcoin is established through digital keys, bitcoin addresses, and digital signatures. The digital keys which can be generated and managed by the user’s wallet software without reference to the blockchain or access to the interne are not stored in the network, but are created and stored by users in a file, simple database, called a wallet.Public key cryptography was invented in the 1970s and is a mathematical foundation for computer and information security. Public key cryptography is used to create a key pair that controls access to bitcoin. The key pair consists of a private key and— derived from it— a public key that’s distinct. The public key is used to receive funds, and the private key is used to sign transactions to spend the funds.The private key must be backed up to prevent loss as this means funds secured by it are lost forever, also private key must remain secret because revealing it to third parties is equivalent to giving them control over the bitcoin secured by that key.The bitcoin address is what appears most commonly in a transaction as the recipient of the funds and bitcoin addresses are almost always encoded as Base58Check which uses 58 characters (a Base58 number system) and a checksum to help human readability, avoid ambiguity, and protect against errors in address transcription and entry.
===== Differences between a public and private key
===== The public key is used to receive funds while the private key is used to sign transactions to spend the funds
===== the public key can be calculated from a private key while a private key cannot be calculated from a public key
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
the public key can be calculated from a private key while a private key cannot be calculated from a public key
----
+++ </div></details> +++
==== Wallets

==== A wallet is an application that serves as the primary user interface. The wallet controls access to a user’s money, managing keys and addresses, tracking the balance, and creating and signing transactions. wallets are containers for private keys and not bitcoin, usually implemented as structured files or simple databases. Depending on whether wallets are related to each other there are two primary types of wallets; nondeterministic wallet or JBOK (Just a bunch of keys) where each key is independently generated from a random number and keys are not related to each other and deterministic wallet where all the keys are derived from a single master key, known as the seed. Keys here are related to each other and can be generated again if one has the original seed. The most commonly used derivation method uses a tree-like structure and is known as a hierarchical deterministic or HD wallet where seeds are encoded as English words or mnemonic code words.
===== Common industry standard for bitcoin wallet technology
===== Mnemonic code words, based on BIP-39
===== HD wallets, based on BIP-32
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
HD wallets, based on BIP-32
----
+++ </div></details> +++
==== Transactions

==== Transactions are the most important part of the bitcoin system. Bitcoin is designed to ensure that transactions can be created, propagated on the network, validated, and finally added to the global ledger of transactions (the blockchain). Transactions are data structures that encode the transfer of value between participants in the bitcoin system.The fundamental building block of a bitcoin transaction is a transaction output which are indivisible chunks of bitcoin currency, recorded on the blockchain, and recognized as valid by the entire network. Transaction outputs consist of two parts: An amount of bitcoin which is denominated in satoshis, and a cryptographic puzzle that determines the conditions required to spend the output. Transactions transmitted over the network or exchanged between applications are serialized that is converting the internal representation of a data structure into a format that can be transmitted one byte at a time. Transaction involves pointer to an UTXO (unspent transaction output) by reference to the transaction hash and an output index, which identifies the specific UTXO in the transaction this is followed by unlocking script, which the wallet constructs in order to satisfy the spending conditions set in the UTXO. Most times, the unlocking script is a digital signature and public key proving ownership of the bitcoin. However, not all unlocking scripts contain signatures, then there is the sequence number. Transaction fees compensate the bitcoin miners for securing the network and also serve as a security mechanism by making it economically infeasible for attackers to flood the network with transactions. A locking script is a spending condition placed on an output: it specifies the conditions that must be met to spend the output in the future. Majority of transactions processed on the bitcoin network spend outputs locked with a Pay-to-Public-Key-Hash or P2PKH script. A digital signature serves three purposes in bitcoin; signature proves that the owner of the private key (owner of fund) has authorized the spending of funds, the proof of authorization is undeniable (nonrepudiation). Thirdly, the signature proves that the transaction (or specific parts of the transaction) have not and cannot be modified by anyone after it has been signed.
===== What are the uses of a digital signature?
===== It proves that the owner of the private key, who is by implication the owner of the funds, has authorized the spending of those funds
===== It shows the proof of authorization is undeniable (nonrepudiation).
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
It shows the proof of authorization is undeniable (nonrepudiation).
----
+++ </div></details> +++
==== Advanced Transactions and Scripting

==== Advanced transaction and scripting involve the use of multisignature scripts and Pay-to-Script-Hash. Multisignature scripts set a condition where a number of public keys (N) are recorded in the script and some of the public keys (M) of those must provide signatures to unlock the funds. For example, a 2-of-3 multisignature is one where three public keys are listed as potential signers and at least two of those must be used to create signatures for a valid transaction to spend the funds. Pay to script hash simpliﬁes the use of complex transaction scripts With P2SH payments, the complex locking script is replaced with its digital ﬁngerprint, a cryptographic hash.Timelocks are restrictions on transactions that only allow spending after a point in time. There are various forms of timelocks; they include Transaction locktime, check lock time verify, relative timelock. Segregated witness (segwit) simply means separating the signature or unlocking script of a speciﬁc transaction.
===== What are the advantage of p2sh over multisignature
===== P2SH has the ability to encode a script hash as an address
===== Complex scripts are replaced by shorter ﬁngerprints in the transaction output, making the transaction smaller.
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Complex scripts are replaced by shorter ﬁngerprints in the transaction output, making the transaction smaller.
----
+++ </div></details> +++
==== The Bitcoin Network

==== Bitcoin is configured as a peer-to-peer (p2p protocol) network on the internet. There are no special nodes in bitcoin and all nodes share equal responsibility but assume different function. Functions in nodes include wallet, miner, full blockchain database, and network routing. Full nodes keep a complete and up-to-date copy of the blockchain; they can verify any transaction without external reference. Simplified payment verification (SPV) nodes or lightweight nodes are a method in which only a portion of the blockchain is preserved and transaction is verified.  The extended bitcoin network includes the network running the bitcoin P2P protocol, as well as nodes running specialized protocols, mostly pool mining nodes and lightweight wallet clients. A Bitcoin Relay Network are overlay networks that provide additional connectivity between nodes with specialized needs. Nodes fluctuate, so a node must continue to discover new nodes as it loses connections and also assist other nodes. Bloom ﬁlters offer an efﬁcient way to express a search pattern while protecting privacy. They are used by SPV nodes.
===== What does the peer-to-peer network design mean
===== It means that the computers that participate in the network are peers to each other
===== There is no server, no centralized service, and no hierarchy within the network
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
There is no server, no centralized service, and no hierarchy within the network
----
+++ </div></details> +++
==== The Blockchain

==== The blockchain data structure is well arranged  and connected list of blocks of transactions. The blockchain can be stored as a ﬂat ﬁle, or in a simple database. Each block within the blockchain is identiﬁed by a hash. The blockchain imagined to be a vertical stack, with blocks placed on top of each other and the ﬁrst block serving as the foundation of the stack. Each block refer to a previous block, known as the parent block, through the previous block hash ﬁeld in the block header. The ﬁrst block ever created is known as the genesis block. When the parent is modiﬁed in any way, the parent’s hash changes. The parent’s changed hash necessitates a change in the previous block hash pointer of the child. A block is a data structure that arrange transactions for inclusion in the blockchain. The block is made of a header, containing metadata and list of transactions.The block header consists of three sets of block metadata. First, there is a reference to a previous block hash, which connects this block to the previous block in the blockchain. The second set of metadata, namely the difﬁculty, timestamp, and nonce, relate to the mining competition . The third piece of metadata is the merkle tree root, a data structure used to efﬁciently summarize all the transactions in the block.The primary identiﬁer of a block is its cryptographic hash. A block can thus be identiﬁed in two ways: by referencing the block hash or by referencing the block height. As a node receives incoming blocks from the network, it will validate these blocks and then link them to the existing blockchain. A merkle tree, also known as a binary hash tree, is a data structure used for summarizing and verifying the integrity of large sets of data. Providing a very efﬁcient process to verify whether a transaction is included in a block. Each block in the bitcoin blockchain contains a summary of all the transactions in the block using a merkle tree. Merkle trees are used extensively by SPV nodes.  There is more than one bitcoin blockchain. The main bitcoin blockchain, the one created by Satoshi Nakamoto on January 3rd, 2009, There are other bitcoin blockchains that are used for testing purposes: at this time testnet, segnet, and regtest. Testnet is used to test any software developed for production on bitcoin’s mainnet. The testnet has all the features of the mainnet. testnet coins are should  be worthless and mining difﬁculty should be low.Segwit was created to aid in development and testing of segregated witness and can be joined by running a special version of Bitcoin Core. Since segwit was added to testnet3, it is no longer necessary to use segnet for testing of segwit features. Regtest, which stands for Regression Testing, is a Bitcoin Core feature that allows you to create a local blockchain for testing purposes. Unlike testnet3, which is a public and shared test blockchain, the regtest blockchains are intended to be run as closed systems for local testing. You launch a regtest blockchain from scratch, creating a local genesis block. You may add other nodes to the network, or run it with a single node only to test the Bitcoin Core software.
===== how does on use a test chain
===== establish a development pipeline.
===== switch to testnet to expose your code to a more dynamic environment
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
switch to testnet to expose your code to a more dynamic environment
----
+++ </div></details> +++
==== Mining and Consensus

==== Mining is the mechanism that support the decentralized clearinghouse, by which transactions are validated and cleared. a decentralized security mechanism is the basis for P2P digital cash. Mining secures the bitcoin system and enables the emergence of network-wide consensus without a central authority. Miners receive two types of rewards in return for the security provided by mining: new coins created with each new block, and transaction fees from all the transactions included in the block. To earn this reward, miners compete to solve a difﬁcult mathematical problem based on a cryptographic hash algorithm. The solution to the problem, called the Proof-of-Work, is included in the new block and acts as proof that the miner expended signiﬁcant computing effort. The maximum amount of newly created bitcoin a miner can add to a block decreases approximately every four years (or precisely every 210,000 blocks). Every transaction may include a transaction fee, in the form of a surplus of bitcoin between the transaction’s inputs and outputs. The winning bitcoin miner gets to keep the change on the transactions included in the winning block. Today, the fees represent 0.5% or less of a bitcoin miner’s income, the vast majority coming from the newly minted bitcoin. However, as the reward decreases over time and the number of transactions per block increases, a greater proportion of bitcoin mining earnings will come from fees. Gradually, the mining reward will be dominated by transaction fees, which will form the primary incentive for miners. Bitcoin are minted during the creation of each block at a ﬁxed and diminishing rate. Each block, generated on average every 10 minutes, contains entirely new bitcoin, created from nothing. Every 210,000 blocks, or approximately every four years, the currency issuance rate is decreased by 50. Bitcoin’s decentralized consensus emerges from the interplay of four processes that occur independently on nodes across the network. before forwarding transactions to its neighbors, every bitcoin node that receives a transaction will ﬁrst verify the transaction. This ensures that only valid transactions are transferred across the network, while invalid transactions are discarded at the ﬁrst node that encounters them. Some of the nodes on the bitcoin network are specialized nodes called miners. The nodes look for new blocks, roaming about the bitcoin network, as do all nodes. The competition among miners effectively ends with the transfer of new block that acts as an announcement of a winner. To miners, receiving a valid new block means someone else won the competition and they lost. However, the end of one round of a competition is also the beginning of the next round. After validating transactions, a bitcoin node will add them to the memory pool, or transaction pool, where transactions await until they can be included (mined) into a block. a node will aggregate the transaction into candidate block. The ﬁrst transaction in any block is called a coinbase transaction. This transaction is constructed by a node and contains  reward for mining effort. Unlike regular transactions, the coinbase transaction does not consume UTXO as inputs. Instead, it has only one input, called the coinbase, which creates bitcoin from nothing. Coinbase transactions do not have an unlocking script (aka, scriptSig) ﬁeld. Instead, this ﬁeld is replaced by coinbase data, which must be between 2 and 100 bytes. Except for the ﬁrst few bytes, the rest of the coinbase data can be used by miners in any way they want; it is arbitrary data. The ﬁrst few bytes of the coinbase used to be arbitrary, but that is no longer the case. As per BIP-34, version-2 blocks (blocks with the version ﬁeld set to 2) must contain the block height index as a script push operation in the beginning of the coinbase ﬁeld. The ﬁnal part of the coinbase data is the ASCII-encoded string /P2SH/ , which indicates that the mining node that mined a block supports the P2SH improvement deﬁned in BIP-16. To construct the block header, the mining node needs to ﬁll in six ﬁelds, as listed in The structure of the block header. Next, the mining node needs to add the Previous Block Hash (also known as prevhash). The next step is to summarize all the transactions with a merkle tree, in order to add the merkle root to the block header. Now that a candidate block has been constructed it is time for  hardware mining rig to mine the block, to ﬁnd a solution to the Proof-of-Work algorithm that makes the block valid. In the simplest terms, mining is the process of hashing the block header repeatedly, changing one parameter, until the resulting hash matches a speciﬁc target. A hash algorithm takes an arbitrary-length data input and produces a ﬁxed-length deterministic result, a digital ﬁngerprint of the input. For any speciﬁc input, the resulting hash will always be the same and can be easily calculated and veriﬁed by anyone implementing the same hash algorithm. The key characteristic of a cryptographic hash algorithm is that it is computationally infeasible to ﬁnd two different inputs that produce the same ﬁngerprint (known as a collision). As a corollary, it is also virtually impossible to select an input in such a way as to produce a desired ﬁngerprint, other than trying random inputs. The miner constructs a candidate block ﬁlled with transactions. Next, the miner calculates the hash of this block’s header and sees if it is smaller than the current target. If the hash is not less than the target, the miner will modify the nonce (usually just incrementing it by one) and try againSuccessfully Mining the Block As mining nodes receive and validate block, they abandon their efforts to ﬁnd a block at the same height and immediately start computing the next block in the chain, using the new block as the parent. By building on top of the newly discovered block, the other miners are essentially voting with their mining power and endorsing the new block and the chain it extends. The third step in bitcoin’s consensus mechanism is independent validation of each new block by every node on the network. As the newly solved block moves across the network, each node performs a series of tests to validate it before propagating it to its peers. The ﬁnal step in bitcoin’s decentralized consensus mechanism is the assembly of blocks into chains and the selection of the chain with the most Proof-of-Work. Once a node has validated a new block, it will then attempt to assemble a chain by connecting the block to the existing blockchain. Nodes maintain three sets of blocks: those connected to the main blockchain, those that form branches off the main blockchain (secondary chains), and ﬁnally, blocks that do not have a known parent in the known chains (orphans). Invalid blocks are rejected as soon as any one of the validation criteria fails and are therefore not included in any chain. The main chain at any time is whichever valid chain of blocks has the most cumulative Proof-of-Work associated with it. Under most circumstances this is also the chain with the most blocks in it, unless there are two equal-length chains and one has more Proof-of-Work. The main chain will also have branches with blocks that are siblings to the blocks on the main chain. These blocks are valid but not part of the main chain. They are kept for future reference, in case one of those chains is extended to exceed the main chain. When a new block is received, a node will try to slot it into the existing blockchain. The node will look at the block’s previous block hash ﬁeld, which is the reference to the block’s parent. Then, the node will attempt to ﬁnd that parent in the existing blockchain. Most of the time, the parent will be the tip of the main chain, meaning this new block extends the main chain. Bitcoin mining is an extremely competitive industry. The hashing power has increased exponentially every year of bitcoin’s existence. Some years the growth has reﬂected a complete change of technology. Miners now collaborate to form mining pools, pooling their hashing power and sharing the reward among thousands of participants. By participating in a pool, miners get a smaller share of the overall reward, but typically get rewarded every day, reducing uncertainty. Most mining pools are managed, meaning that there is a company or individual running a pool server. The owner of the pool server is called the pool operator
===== What are some of the criteria to be met before a block can be verified
===== A matching transaction in the pool, or in a block in the main branch, must exist.
===== For each input, the referenced output must exist and cannot already be spent.
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
For each input, the referenced output must exist and cannot already be spent.
----
+++ </div></details> +++
==== Bitcoin Security

==== . A bitcoin wallet, containing your keys, can be backed up like any ﬁle. A decentralized system like bitcoin pushes the responsibility and control to the users. Because security of the network is based on Proof-of-Work, not access control, the network can be open and no encryption is required for bitcoin trafﬁc. A bitcoin transaction authorizes only a speciﬁc value to a speciﬁc recipient and cannot be forged or modiﬁed. It does not reveal any private information, such as the identities of the parties, and cannot be used to authorize additional payments. Bitcoin security design is different. In bitcoin, the consensus system creates a trusted public ledger that is completely decentralized. A correctly validated blockchain uses the genesis block as the root of trust, building a chain of trust up to the current block. Bitcoin systems can and should use the blockchain as their root of trust. Ultimately, the only thing that should be explicitly trusted is a fully validated blockchain. most users are more comfortable with physical security than information security, a very effective method for protecting bitcoin is to convert them into physical form. Bitcoin keys are nothing more than long numbers. This means that they can be stored in a physical form, such as printed on paper or etched on a metal coin. A set of bitcoin keys that is printed on paper is called a paper wallet,. Keeping bitcoin ofﬂine is called cold storage and it is one of the most effective security techniques. A cold storage system is one where the keys are generated on an ofﬂine system and stored ofﬂine either on paper or on digital media, such as a USB memory stick. In the long term, bitcoin security increasingly will take the form of hardware tamper-proof wallets. Unlike a smartphone or desktop computer, a bitcoin hardware wallet has just one purpose: to hold bitcoin securely. Prudent users will keep only a small fraction, perhaps less than 5%, of their bitcoin in an online or mobile wallet as pocket change. The rest should be split between a few different storage mechanisms, such as a desktop wallet and ofﬂine (cold storage). When storing a large amounts of bitcoin, a multisignature bitcoin address should be considered. Multisignature addresses secure funds by requiring more than one signature to make a payment. The signing keys should be stored in a number of different locations and under the control of different people. Multisignature addresses can also offer redundancy, where a single person holds several keys that are stored in different locations. If you have a lot of bitcoin, you should consider sharing access details with a trusted relative or lawyer. A more complex survivability scheme can be set up with multi-signature access and estate planning through a lawyer specialized as a digital asset executor.
===== What are the things I should avoid when storing my bitcoin
===== Do not store all your bitcoin in one wallet, diversify i.e put your bitcoin in different wallet
===== Do not take your transaction off blockchain because improperly secured centralized ledgers can be falsiﬁed, diverting funds and depleting reserves, unnoticed.
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Do not take your transaction off blockchain because improperly secured centralized ledgers can be falsiﬁed, diverting funds and depleting reserves, unnoticed.
----
+++ </div></details> +++
==== Blockchain Applications

==== The bitcoin blockchain can become an application platform offering trust services to applications, such as smart contracts, far surpassing the original purpose of digital currency and payments. When operating correctly and over the long term, the bitcoin system offers certain guarantees, which can be used as building blocks to create applications. This is a blockchain application which refers to a set of similar technologies that use bitcoin transactions to record the creation, ownership, and transfer of extrinsic assets other than bitcoin (assets that are not stored directly on the bitcoin blockchain). Colored coins are used to track digital assets as well as physical assets held by third parties and traded through colored coins certiﬁcates of ownership. Digital asset colored coins can represent intangible assets. Counterparty is a protocol layer built on top of bitcoin. The Counterparty protocol, similar to colored coins, offers the ability to create and trade virtual assets and tokens. In addition, Counterparty offers a decentralized exchange for assets. Counterparty is also implementing smart contracts, based on the Ethereum Virtual Machine (EVM). Payment channels are a trustless mechanism for exchanging bitcoin transactions between two parties, outside of the bitcoin blockchain. These transactions, which would be valid if settled on the bitcoin blockchain, are held off-chain instead, acting as promissory notes for eventual batch settlement. Because the transactions are not settled, they can be exchanged without the usual settlement latency, allowing extremely high transaction, low (submillisecond) latency, and ﬁne (satoshi-level) granularity. State channels are virtual constructs represented by the exchange of state between two parties, outside of the blockchain. Through a transaction that locks a shared state on the blockchain. This is called the funding transaction or anchor transaction. This single transaction must be transmitted to the network and mined to establish the channel. The two parties then exchange signed transactions, called commitment transactions, that alter the initial state. These transactions are valid transactions but are held off-chain by each party pending the channel closure. When exchanging commitment transactions the two parties also invalidate the previous states. Finally, the channel can be closed either cooperatively or unilaterally. In the entire lifetime of the channel, only two transactions need to be submitted for mining on the blockchain: the funding and settlement transactions. In between these two states, the two parties can exchange any number of commitment transactions that are never seen by anyone else, nor submitted to the blockchain. A Hash Time Lock Contract, or HTLC, is a type of Payment channels that can be further extended with a special type of smart contract that allows the participants to commit funds to a redeemable secret, with an expiration time.  And it is used in both bidirectional and routed payment channels. The Lightning Network is a proposed routed network of bidirectional payment channels connected end-to- end. A network like this can allow any participant to route a payment from channel to channel without trusting any of the intermediaries.
===== What are the guarantees offered by bitcoin
===== Once a transaction is recorded in the blockchain and sufﬁcient work has been added with subsequent blocks, the transaction’s data becomes immutable.
===== Digital signatures, validated in a decentralized network, offer authorization guarantees.
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Digital signatures, validated in a decentralized network, offer authorization guarantees.
----
+++ </div></details> +++
