== Bitcoin
=== Bitcoin Development (source)
Link: https://lopp.net/bitcoin.html


https://medium.com/@nik5ter/explain-bitcoin-like-im-five-73b4257ac833[Explain Bitcoin Like I'm Five]

The story for a child who would like to know more how to digitize apple transferring.
Good analogy with tokenization of economy. Easy to understand blockchain.


==== Who is uncle Tommy?
===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

https://www.upfolio.com/ultimate-bitcoin-guide[Bitcoin Explained]

It is a clever system that allows complete strangers to securely send money directly between each other – no trust required! Amazingly, no third party (like a bank) is required, either. 

==== What makes Bitcoin so unique?
===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

https://lopp.net/pdf/bitcoin.pdf[The Bitcoin Whitepaper written by Satoshi Nakamoto]

The description of the innovative technology in mathematical terms with explanation logic of work, privacy, payment verification. 


==== The description of the innovative technology in mathematical terms with explanation logic of work, privacy, payment verification. 

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

http://fermatslibrary.com/s/bitcoin[The Bitcoin Whitepaper with annotations]

Questions and comments to the whitepaper of famous cryptocurrency by readers of Ferman’s library. Interesting positions of readers and disputes.


==== Escrow with bitcoin? Is this possible?
 

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

http://www.coindesk.com/information/[Beginner's Guide to Bitcoin by CoinDesk]

You will get answers to the next questions 
What is Bitcoin? It's a decentralized digital currency Why Use Bitcoin? It's fast, cheap to use, and secure How Can I Buy Bitcoin? From an exchange or an individual, How to Buy Bitcoin in the UK, Buying bitcoin in the UK,  How to Store Your Bitcoin  Use a digital or paper wallet


==== What Can You Buy with Bitcoin?
===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

http://blog.oleganza.com/post/85111558553/bitcoin-is-like[Bitcoin is Like…]

Version and controversion. Comparing and analyze of Bitcoin states and forms. Amazing idea to tell about a complex subject. 

==== Is Bitcoin gold of the new era? 
===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

https://www.rhymeswithfiat.com/[A Bitcoin Webcomic (with educational notes)]

Witty comics about talks between heroes of Ethereum and Bitcoin.Short stories with funny culmination. 


==== 
===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

https://www.bitcoindesigned.com/[Bitcoin Infographics]

Well designed infographics that demonstrate in an easy way different conceptions of Bitcoin. You will get the answers is Bitcoin anonymous or about Byzantine general problem. 


==== 
===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

https://www.youtube.com/watch?v=ZKwqNgG-Sv4[The Trust Machine: The Story of Bitcoin]



==== 
===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

https://readingbitcoin.org/[Reading Bitcoin - translated articles]

The aggregator of articles from the famous platform like blockstream.com written by different bloggers. Good explanation of material with visualization of not trivial technologies and processes. 


