== Ethereum Development (source)
=== Ethereum Development Tools


Link: http://solidity.readthedocs.io/en/latest/

Solidity is an object-oriented, high-level language for implementing smart contracts. Smart contracts are programs which govern the behavior of accounts within the Ethereum state.


==== What it is EVM?

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----
Ethereum Virtual machine
----
+++ </div></details> +++

Link:https://remix.ethereum.org/

Remix is a powerful, open source tool that helps you write Solidity contracts straight from the browser. Written in JavaScript, Remix supports both usage in the browser and locally.


==== What is the main goal of Remix?

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

Link: https://faucet.rinkeby.io/

Rinkeby is a Proof-of-Authority network, so uses a different consensus mechanism to the main net. The Ropsten testnet is Proof-of-Work, so more similar to the public main net.
Rinkeby faucet provide you with some test coins for testnet.


==== How you can get test coins in Rinkeby faucet?
===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

Link: https://github.com/ethereum/go-ethereum/wiki/geth

geth is the command line interface for running a full ethereum node implemented in Go. It is the main deliverable of the Frontier Release


==== How you can use geth in your dApp development?

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

Link: https://www.parity.io/

Parity develops cutting-edge blockchain technologies to foster innovation such as Parity Ethereum, Parity Bitcoin, Polkadot and others.


==== Why Kovan so useful for development?

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

Link: https://github.com/trufflesuite/ganache

A personal blockchain for Ethereum development you can use to deploy contracts, develop your applications, and run tests. It is available as both a desktop application as well as a command-line tool (formerly known as the TestRPC). Ganache is available for Windows, Mac, and Linux.


==== How many addresses Ganache create by default after deployment?

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

Link: https://github.com/ethereum/web3.js/

Ethereum compatible JavaScript API which implements the Generic JSON RPC spec. It's available on npm as a node module, for Bower and component as embeddable scripts, and as a meteor.js package.


==== What is the main purpose of Web.js in blockchain development?
===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

Link: https://github.com/ethereum/web3.py

Web3.py is a python library for interacting with Ethereum. Its API is derived from the Web3.jsJavascript API and should be familiar to anyone who has used web3.js.



==== What for you need to reactivate your virtualenv while using Web3.py
===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

Link: http://truffleframework.com/boxes/

Truffle Boxes are helpful boilerplates that allow you to focus on what makes your dapp unique. In addition to Truffle, Truffle Boxes can contain other helpful modules, Solidity contracts & libraries, front-end views and more; all the way up to complete example dapps.

==== What the most appealing box from truffle suite to you?

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
--------
+++ </div></details> +++

Link: https://github.com/truffle-box/drizzle-box

This box comes with everything you need to start using smart contracts from a react app with Drizzle. It includes drizzle, drizzle-react and drizzle-react-components to give you a complete overview of Drizzle's capabilities.


==== How to verify that Drizzle working properly?

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++


Link: https://github.com/OpenZeppelin/openzeppelin-solidity

OpenZeppelin is a library for secure smart contract development. It provides implementations of standards like ERC20 and ERC721 which you can deploy as-is or extend to suit your needs, as well as Solidity components to build custom contracts and more complex decentralized systems.


==== Why OpenZeppelin framework is so secured?

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

Link: https://ipfs.io/docs/

When you use IPFS, you don’t only download a file from someone else, but your computer can help distribute it, too — when your friend a few blocks away needs the same Wikipedia page, they might be as likely to get it from you like your neighbor.
IPFS makes this possible for web pages, but also for any kind of file a computer might store, whether it’s an MS Word document, an e-mail, an MP3 file, or even a database record.


==== What is the difference between IPFS and MFS?

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++


Link: http://swarm-gateways.net/

Swarm: Serverless Hosting Incentivised Peer-To-Peer Storage And Content Distribution


==== How to verify that your local Swarm node is running?

===== 
===== 
===== 
===== 
===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

Link: https://github.com/ethereum/wiki/wiki/Whisper

In a nutshell whisper is a communication protocol for DApps to communicate with each other.
Some existing solutions are MQ: A distributed messaging system, no inherent privacy safeguards.Bitmessage: Similar in the basic approach of P2P network exchanging messages with baseline PKI for dark comms. 


==== For what type of dApps Whisper can be useful?

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++

Link: https://metamask.io/

MetaMask is a bridge that allows you to visit the distributed web of tomorrow in your browser today. It allows you to run Ethereum dApps right in your browser without running a full Ethereum node.


==== What does it mean “seed words”?

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++


Link: https://etherscan.io/

Etherscan is the leading BlockExplorer for the Ethereum Blockchain. A BlockExplorer is basically a search engine that allows users to easily lookup, confirm and validate transactions that have taken place on the Ethereum Blockchain. We are independently operated and developed by a team of individuals who are truly passionate and excited about the kinds of decentralized information and infrastructure applications that Ethereum makes possible. 


==== Where you can find information about published tokens?

===== 
===== 
+++ <details><summary> +++
    Answer
    +++ </summary><div> +++
----

----
+++ </div></details> +++
